name: Build Release - Gnome <= 44
on:
  push:
    branches:
      - gnome-before-45

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gnome-before-45
      - name: Create Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq LeftClock@adityashrivastava.tk.zip extension.js metadata.json
      - name: Upload Zip as Artifact
        id: arti
        uses: actions/upload-artifact@v2
        with:
          name: LeftClock@adityashrivastava.tk.zip
          path: ./LeftClock@adityashrivastava.tk.zip
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.2.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: phish108/autotag-action@v1.1.55
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: true
          dry-run: true
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.tagger.outputs.new-tag }}
          name: LeftClock - v${{ steps.tagger.outputs.new-tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          commit: gnome-before-45
          artifacts: './LeftClock@adityashrivastava.tk.zip'
