name: Build Release - Gnome <= 44
on:
  push:
    branches:
      - gnome-before-45

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.2.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: phish108/autotag-action@v1.1.55
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
          dry-run: "true"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tagger.outputs.new-tag }}
          name: Release - Gnome<=44
          body: ${{ steps.changelog.outputs.changelog }}
