name: Build Release - Gnome <= 44
on:
  push:
    branches:
      - gnome-before-45

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Checkout Code
        uses: actions/checkout@v3
      - name: Generate changelog #Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.2.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release #Create a lease based on a new tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} - Gnome<=44
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
