name: Build Release
on:
  push:
    branches:
      - gnome-before-45

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Checkout Code
        uses: actions/checkout
      - name: Generate changelog #Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator
        with:
          myToken: ${{ secrets.GIT_PAT_TOKEN }}
      - name: Create Release #Create a lease based on a new tag
        id: create_release
        uses: actions/create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} - Gnome<=44
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
